package:
  name: cachannel
  version: 3.0.0a3

source:
  # build from source tree (for conda-build > 1.9)
  path: ..
  
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - CaChannel

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  source_files:
    - tests/ca_test.py
    - tests/test.db

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    # - nose
    - setuptools
    - epics-base
    - numpy

about:
  home: https://pypi.python.org/pypi/CaChannel
  license: BSD License
  summary: 'CaChannel Interface to EPICS'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
