package:
  name: cachannel
  version: 3.1.2

source:
  path: ..
  patches:
    - readline.patch # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - wheel
    - epics-base
    - enum34 # [py2k]

  run:
    - python
    - enum34 # [py2k]

test:
  imports:
    - CaChannel

  requires:
    - setuptools
    - epics-base
    - numpy
    - enum34 # [py2k]

  source_files:
    - tests/ca_test.py
    - tests/test.db

about:
  home: https://pypi.python.org/pypi/CaChannel
  license: BSD License
  summary: 'CaChannel Interface to EPICS'
