name: "Build Conda Packages"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: conda build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          auto-activate-base: true
          activate-environment: ""
          conda-build-version: 25
      - name: Setup Xcode and SDK on macOS
        if: runner.os == 'macOS'
        run: |
            if [[ $RUNNER_ARCH == "ARM64" ]]; then
                MACOS_SDK=MacOSX11.0.sdk
            else
                MACOS_SDK=MacOSX10.9.sdk
            fi
            curl -OL https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/${MACOS_SDK}.tar.xz
            sudo tar xf ${MACOS_SDK}.tar.xz -C /opt
            printf "CONDA_BUILD_SYSROOT:\n    - /opt/${MACOS_SDK}\n" >> conda-recipe/conda_build_config.yaml
      - name: Build macOS
        if: runner.os == 'macOS'
        run: |
            mkdir packages
            conda info
            conda config --add channels paulscherrerinstitute
            conda build --output-folder packages conda-recipe
      - name: Build Linux
        if: runner.os == 'linux'
        uses: docker://conda/miniconda3-centos7:latest
        with:
          args: bash -c "conda config --add channels paulscherrerinstitute;conda install conda-build;conda info;cd /github/workspace;mkdir packages;conda build --output-folder packages conda-recipe"
      - name: Upload Anaconda
        run: |
            conda install anaconda-client
            [[ -z ${MY_CONDA_TOKEN} ]] || anaconda -v -t ${MY_CONDA_TOKEN} upload --force packages/*/*.tar.bz2
        env:
          MY_CONDA_TOKEN: ${{ secrets.MY_CONDA_TOKEN }}
      - name: Upload Conda Artifact
        uses: actions/upload-artifact@v4
        with:
          name: conda-packages-${{ runner.os }}-${{ runner.arch }}
          path: packages/*/*.tar.bz2
          retention-days: 1
      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-packages-${{ runner.os }}-${{ runner.arch }}
          path: |
              packages/*/*.whl
              wheelhouse/*.whl
          retention-days: 1
